name = "Drill"
uuid = "49b37b9d-a8e6-4364-9144-4677bcb8a7f0"
version = "0.0.1"
authors = ["Kristian Holme <holme.kristian@gmail.com>"]

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
OneHotArrays = "0b1bfda6-eb8a-41d2-88d8-f5af5cad476f"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
Octavian = "6fd5a793-0b7e-452c-907f-f8bfe9c57db4"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[weakdeps]
DearDiary = "bcf306fc-d39d-4f25-b732-26abcc96baf2"
TensorBoardLogger = "899adc3e-224a-11e9-021f-63837185c80f"
Wandb = "ad70616a-06c9-5745-b1f1-6a5f42545108"

[extensions]
Drill_DearDiaryExt = ["DearDiary"]
Drill_TensorBoardLoggerExt = ["TensorBoardLogger"]
Drill_WandbExt = ["Wandb"]

[compat]
Accessors = "0.1"
OneHotArrays = "0.2"
ChainRulesCore = "1"
ComponentArrays = "0.15"
DataStructures = "0.18.22, 0.19"
DearDiary = "0.3"
FileIO = "1"
Functors = "0.5.2"
JLD2 = "0.5.13, 0.6"
LinearAlgebra = "1"
Logging = "1"
LoopVectorization = "0.12"
Lux = "1"
MLUtils = "0.4"
Octavian = "0.3"
Optimisers = "0.4"
ProgressMeter = "1"
Random = "1"
Reexport = "1"
Statistics = "1"
StatsBase = "0.34"
TensorBoardLogger = "0.1"
TimerOutputs = "0.5"
Wandb = "0.5"
julia = "1.10"
